sacctmgr create user name=lebarbanchon account=lebarbanchon
sacctmgr create user name=melbourne account=melbourne
sacctmgr create user name=moscato account=moscato
sacctmgr create user name=pope account=pope
sacctmgr create user name=poege account=poege
sacctmgr create user name=gauthier account=gauthier
sacctmgr create user name=3144860 account=3144860
sacctmgr create user name=3173139 account=3173139
sacctmgr create user name=polak account=polak
sacctmgr create user name=goerlach account=goerlach
sacctmgr create user name=peruginig account=peruginig
sacctmgr create user name=pratom account=pratom
sacctmgr create user name=lucchinial account=lucchinial
sacctmgr create user name=misani account=misani
sacctmgr create user name=venzinm account=venzinm
sacctmgr create user name=achillib account=achillib
sacctmgr create user name=dalbarco account=dalbarco
sacctmgr create user name=garnier account=garnier
sacctmgr create user name=bologni account=bologni
sacctmgr create user name=unwith account=unwith
sacctmgr create user name=schwantje account=schwantje
sacctmgr create user name=elass account=elass
sacctmgr create user name=3129843 account=3129843
sacctmgr create user name=buendia account=buendia
